# -*- coding: utf-8 -*-
"""btree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aD4gWSDxNBs6j2c1biaSboZR88IhgZpo
"""

# src/btree.py

class BTreeNode:
    """
    B-tree의 노드를 정의하는 클래스입니다.
    내부 노드에서도 검색이 종료될 수 있으므로 (Key, RID) 쌍을 모두 저장합니다.
    """
    def __init__(self, is_leaf=False):
        self.is_leaf = is_leaf
        self.keys = []       # 학번(Student ID)을 저장하는 리스트
        self.rids = []       # 실제 데이터의 배열 인덱스(RID)를 저장하는 리스트
        self.children = []   # 자식 노드 포인터 리스트 (길이는 항상 keys.length + 1)

    def find_index(self, key):
        """
        [최적화 포인트] 노드 내부 탐색 시 선형 탐색(O(d)) 대신 이진 탐색(O(log d))을 사용합니다.
        표준 라이브러리(bisect) 사용을 피하기 위해 직접 구현했습니다.
        주어진 key가 들어갈(또는 존재하는) 첫 번째 인덱스를 반환합니다.
        """
        left, right = 0, len(self.keys) - 1
        while left <= right:
            mid = (left + right) // 2
            if self.keys[mid] < key:
                left = mid + 1
            else:
                right = mid - 1
        return left


class BTree:
    """
    차수(d)를 파라미터로 받는 B-tree 메인 클래스입니다.
    최대 자식 수 = d, 최대 키 수 = d - 1 입니다.
    """
    def __init__(self, order):
        if order < 3:
            raise ValueError("B-tree order must be at least 3.")
        self.order = order
        self.max_keys = order - 1
        self.min_keys = (order + 1) // 2 - 1
        self.root = BTreeNode(is_leaf=True)
        self.split_count = 0  # 보고서의 성능 분석(Parameter Tuning)을 위한 트래커

    def search(self, key):
        """특정 Key(학번)를 검색하여 RID를 반환합니다. 없으면 None을 반환합니다."""
        return self._search_node(self.root, key)

    def _search_node(self, node, key):
        i = node.find_index(key)
        # 현재 노드에서 키를 찾은 경우 (내부 노드에서 탐색 종료 가능)
        if i < len(node.keys) and node.keys[i] == key:
            return node.rids[i]

        # 키를 못 찾았는데 리프 노드인 경우
        if node.is_leaf:
            return None

        # 자식 노드로 재귀 탐색
        return self._search_node(node.children[i], key)

    def insert(self, key, rid):
        """(Key, RID) 쌍을 트리에 삽입합니다."""
        root = self.root
        # 루트 노드가 꽉 찼을 경우, 트리의 높이를 1 증가시키고 루트를 분할합니다.
        if len(root.keys) == self.max_keys:
            new_root = BTreeNode(is_leaf=False)
            new_root.children.append(self.root)
            self._split_child(new_root, 0, self.root)
            self.root = new_root
            self._insert_non_full(self.root, key, rid)
        else:
            self._insert_non_full(root, key, rid)

    def _insert_non_full(self, node, key, rid):
        """가득 차지 않은 노드에 안전하게 삽입하는 헬퍼 메서드입니다."""
        i = node.find_index(key)

        # 이미 존재하는 키일 경우 업데이트 (본 과제에서는 중복이 없다고 가정 가능)
        if i < len(node.keys) and node.keys[i] == key:
            node.rids[i] = rid
            return

        if node.is_leaf:
            # 리프 노드면 해당 위치에 삽입
            node.keys.insert(i, key)
            node.rids.insert(i, rid)
        else:
            # 내부 노드면 자식으로 내려가야 함
            child = node.children[i]
            # 내려갈 자식 노드가 꽉 찼다면 미리 분할 (Preemptive Split)
            if len(child.keys) == self.max_keys:
                self._split_child(node, i, child)
                # 분할 후, 새로 올라온 키와 비교하여 어느 자식으로 갈지 재결정
                if key > node.keys[i]:
                    i += 1
            self._insert_non_full(node.children[i], key, rid)

    def _split_child(self, parent, index, child):
        """
        꽉 찬 자식 노드(child)를 둘로 쪼개고, 중간값을 부모(parent)로 올립니다.
        """
        self.split_count += 1  # 분할 발생 카운트 증가

        new_node = BTreeNode(is_leaf=child.is_leaf)
        mid_index = self.max_keys // 2

        # 중간값 추출
        mid_key = child.keys[mid_index]
        mid_rid = child.rids[mid_index]

        # 새 노드에 데이터 분배 (오른쪽 절반)
        new_node.keys = child.keys[mid_index + 1:]
        new_node.rids = child.rids[mid_index + 1:]
        child.keys = child.keys[:mid_index]
        child.rids = child.rids[:mid_index]

        if not child.is_leaf:
            new_node.children = child.children[mid_index + 1:]
            child.children = child.children[:mid_index + 1]

        # 부모 노드에 중간값 및 새로운 자식 포인터 연결
        parent.keys.insert(index, mid_key)
        parent.rids.insert(index, mid_rid)
        parent.children.insert(index + 1, new_node)

# ==========================================
    # DELETE LOGIC (Bottom-Up Architecture)
    # ==========================================
    def delete(self, key):
        if not self.root.keys:
            return False
        self._delete_recursive(self.root, None, 0, key)
        if len(self.root.keys) == 0 and not self.root.is_leaf:
            self.root = self.root.children[0]

    def _delete_recursive(self, node, parent, parent_idx, key):
        i = node.find_index(key)
        
        # 1. 키를 찾은 경우
        if i < len(node.keys) and node.keys[i] == key:
            if node.is_leaf:
                node.keys.pop(i)
                node.rids.pop(i)
            else:
                sk, sr = self._get_successor(node, i)
                node.keys[i] = sk
                node.rids[i] = sr
                self._delete_recursive(node.children[i+1], node, i+1, sk)
        # 2. 키를 찾지 못한 경우 자식으로 이동
        else:
            if node.is_leaf:
                return
            self._delete_recursive(node.children[i], node, i, key)

        # 3. [핵심] 재귀가 풀려 올라오면서 Underflow(최소 키 개수 미만) 체크 및 복구
        if parent and len(node.keys) < self.min_keys:
            self._handle_underflow(node, parent, parent_idx)

    def _get_successor(self, node, index):
        curr = node.children[index+1]
        while not curr.is_leaf:
            curr = curr.children[0]
        return curr.keys[0], curr.rids[0]

    def _handle_underflow(self, node, parent, i):
        # 1. 왼쪽 형제에게서 빌려오기
        if i > 0 and len(parent.children[i-1].keys) > self.min_keys:
            left = parent.children[i-1]
            node.keys.insert(0, parent.keys[i-1])
            node.rids.insert(0, parent.rids[i-1])
            parent.keys[i-1] = left.keys.pop()
            parent.rids[i-1] = left.rids.pop()
            if not node.is_leaf:
                node.children.insert(0, left.children.pop())
            return
            
        # 2. 오른쪽 형제에게서 빌려오기
        if i < len(parent.children) - 1 and len(parent.children[i+1].keys) > self.min_keys:
            right = parent.children[i+1]
            node.keys.append(parent.keys[i])
            node.rids.append(parent.rids[i])
            parent.keys[i] = right.keys.pop(0)
            parent.rids[i] = right.rids.pop(0)
            if not node.is_leaf:
                node.children.append(right.children.pop(0))
            return

        # 3. 빌려올 수 없다면 형제와 병합 (Merge)
        if i > 0:
            self._merge(parent, i-1)
        else:
            self._merge(parent, i)

    def _merge(self, parent, i):
        left = parent.children[i]
        right = parent.children[i+1]

        # 부모의 구분 키를 왼쪽 자식으로 내림
        left.keys.append(parent.keys.pop(i))
        left.rids.append(parent.rids.pop(i))
        
        # 오른쪽 자식의 모든 데이터를 왼쪽 자식에 합침
        left.keys.extend(right.keys)
        left.rids.extend(right.rids)
        if not left.is_leaf:
            left.children.extend(right.children)
            
        # 불필요해진 오른쪽 자식 포인터 제거
        parent.children.pop(i+1)