# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aD4gWSDxNBs6j2c1biaSboZR88IhgZpo
"""

# main.py

import argparse
import os
import sys

# src 폴더 내부의 모듈들을 임포트하기 위해 경로 추가
sys.path.append(os.path.join(os.path.dirname(__file__), 'src'))

from experiments import load_data, measure_workloads, run_edge_case

def main():
    # ---------------------------------------------------------
    # 조교님을 위한 친절한 CLI 인터페이스 구성
    # ---------------------------------------------------------
    parser = argparse.ArgumentParser(
        description="UNIST CSE321 Project #1: Index Structures Evaluator",
        formatter_class=argparse.RawTextHelpFormatter
    )

    parser.add_argument(
        '-d', '--order',
        type=int,
        default=5,
        help="트리의 차수 (Fan-out order d)를 설정합니다. (기본값: 5)\n예시: python main.py -d 10"
    )

    parser.add_argument(
        '--edge',
        action='store_true',
        help="[Bonus] B-tree와 B*-tree의 순차 삽입(Sequential Insertion) 엣지 케이스 실험을 추가로 실행합니다."
    )

    args = parser.parse_args()

    # 차수(d) 유효성 검사
    if args.order < 3:
        print("[에러] 트리의 차수(d)는 최소 3 이상이어야 합니다.")
        sys.exit(1)

    print("=" * 60)
    print(" CSE321 Project #1: B-Tree, B*-Tree, B+-Tree Performance")
    print("=" * 60)

    # 1. 데이터 로드 (src/experiments.py의 로직 호출)
    csv_path = os.path.join(os.path.dirname(__file__), 'data', 'students.csv')
    print(f"[*] 데이터셋 로딩 중... ({csv_path})")

    try:
        keys = load_data(csv_path)
        print(f"[*] 성공: {len(keys):,} 개의 학생 레코드를 메모리에 로드했습니다.")
    except Exception as e:
        print(f"[에러] 데이터를 불러오는 중 문제가 발생했습니다: {e}")
        sys.exit(1)

    # 2. 필수 워크로드 실행 [cite: 41]
    measure_workloads(args.order, keys)

    # 3. 보너스 엣지 케이스 실행 (CLI에 --edge 플래그가 있을 경우) [cite: 70, 71]
    if args.edge:
        run_edge_case(args.order)

    print(f"\n{'='*60}")
    print(" ALL EXPERIMENTS COMPLETED SUCCESSFULLY.")
    print(f"{'='*60}")

if __name__ == "__main__":
    main()