# -*- coding: utf-8 -*-
"""bplus_tree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aD4gWSDxNBs6j2c1biaSboZR88IhgZpo
"""

# src/bplus_tree.py

class BPlusInternalNode:
    """
    B+-tree의 내부 노드 (Internal Node)
    데이터(RID) 없이 Key와 자식 포인터만 저장하여 라우팅 역할만 수행합니다.
    """
    def __init__(self):
        self.is_leaf = False
        self.keys = []
        self.children = []

    def find_index(self, key):
        """[최적화] 노드 내부 이진 탐색 (O(log d))"""
        left, right = 0, len(self.keys) - 1
        while left <= right:
            mid = (left + right) // 2
            if self.keys[mid] <= key:  # B+-tree 라우팅을 위해 작거나 같을 때 오른쪽으로
                left = mid + 1
            else:
                right = mid - 1
        return left


class BPlusLeafNode:
    """
    B+-tree의 리프 노드 (Leaf Node)
    실제 데이터(RID)를 모두 저장하며, 범위 검색을 위한 next_leaf 포인터를 가집니다.
    """
    def __init__(self):
        self.is_leaf = True
        self.keys = []
        self.rids = []
        self.next_leaf = None  # Range Scan을 위한 Linked List 포인터

    def find_index(self, key):
        left, right = 0, len(self.keys) - 1
        while left <= right:
            mid = (left + right) // 2
            if self.keys[mid] < key:
                left = mid + 1
            else:
                right = mid - 1
        return left


class BPlusTree:
    """
    차수(d)를 파라미터로 받는 B+-tree 메인 클래스입니다.
    """
    def __init__(self, order):
        if order < 3:
            raise ValueError("B+-tree order must be at least 3.")
        self.order = order
        self.max_keys = order - 1
        self.min_keys_leaf = (order + 1) // 2 - 1
        self.min_keys_internal = (order + 1) // 2 - 1
        self.root = BPlusLeafNode()
        self.split_count = 0

    # ==========================================
    # SEARCH LOGIC (Must always reach leaf nodes)
    # ==========================================
    def search(self, key):
        """항상 리프 노드까지 도달한 후 검색을 수행합니다."""
        curr = self.root
        while not curr.is_leaf:
            i = curr.find_index(key)
            curr = curr.children[i]

        # 리프 노드 도달 후 키 확인
        i = curr.find_index(key)
        if i < len(curr.keys) and curr.keys[i] == key:
            return curr.rids[i]
        return None

    def range_query(self, start_key, end_key):
        """
        [필수 요구사항] B+-tree의 꽃, 링크드 리스트를 활용한 O(N) 범위 검색
        start_key부터 end_key 범위 안의 모든 (Key, RID) 쌍을 리스트로 반환합니다.
        """
        result = []
        # 1. start_key가 있는(또는 있어야 할) 리프 노드를 찾습니다.
        curr = self.root
        while not curr.is_leaf:
            i = curr.find_index(start_key)
            curr = curr.children[i]

        # 2. 링크드 리스트를 타고 가며 조건에 맞는 데이터를 긁어모읍니다.
        while curr is not None:
            for i in range(len(curr.keys)):
                if curr.keys[i] > end_key:
                    return result  # 상한선 초과 시 즉시 탐색 종료
                if curr.keys[i] >= start_key:
                    result.append((curr.keys[i], curr.rids[i]))
            # 다음 리프 노드로 점프 (O(1) 비용)
            curr = curr.next_leaf

        return result

    # ==========================================
    # INSERT LOGIC
    # ==========================================
    def insert(self, key, rid):
        overflow = self._insert_recursive(self.root, key, rid)

        if overflow:
            self.split_count += 1
            up_key, new_child = overflow
            new_root = BPlusInternalNode()
            new_root.keys = [up_key]
            new_root.children = [self.root, new_child]
            self.root = new_root

    def _insert_recursive(self, node, key, rid):
        if node.is_leaf:
            i = node.find_index(key)
            if i < len(node.keys) and node.keys[i] == key:
                node.rids[i] = rid  # Update
                return None

            node.keys.insert(i, key)
            node.rids.insert(i, rid)

            # 리프 노드 오버플로우
            if len(node.keys) > self.max_keys:
                return self._split_leaf(node)
            return None
        else:
            i = node.find_index(key)
            child = node.children[i]
            overflow = self._insert_recursive(child, key, rid)

            if overflow:
                up_key, new_child = overflow
                self.split_count += 1

                # 올라온 키를 현재 내부 노드에 삽입
                insert_idx = node.find_index(up_key)
                node.keys.insert(insert_idx, up_key)
                node.children.insert(insert_idx + 1, new_child)

                # 내부 노드 오버플로우
                if len(node.keys) > self.max_keys:
                    return self._split_internal(node)
            return None

    def _split_leaf(self, leaf):
        """리프 노드 분할: 중간값은 부모로 복사되고, 리프에는 남습니다."""
        new_leaf = BPlusLeafNode()
        mid_idx = len(leaf.keys) // 2

        # 중간값 복사 (Copy up)
        up_key = leaf.keys[mid_idx]

        new_leaf.keys = leaf.keys[mid_idx:]
        new_leaf.rids = leaf.rids[mid_idx:]
        leaf.keys = leaf.keys[:mid_idx]
        leaf.rids = leaf.rids[:mid_idx]

        # [핵심] 리프 노드 간의 포인터 재설정 (Linked List 갱신)
        new_leaf.next_leaf = leaf.next_leaf
        leaf.next_leaf = new_leaf

        return (up_key, new_leaf)

    def _split_internal(self, node):
        """내부 노드 분할: 중간값은 부모로 완전히 이동합니다."""
        new_node = BPlusInternalNode()
        mid_idx = len(node.keys) // 2

        # 중간값 이동 (Push up)
        up_key = node.keys[mid_idx]

        new_node.keys = node.keys[mid_idx + 1:]
        new_node.children = node.children[mid_idx + 1:]

        node.keys = node.keys[:mid_idx]
        node.children = node.children[:mid_idx + 1]

        return (up_key, new_node)

    # ==========================================
    # DELETE LOGIC (Leaf Focus)
    # ==========================================
    def delete(self, key):
        if not self.root.keys:
            return False

        self._delete_recursive(self.root, None, 0, key)

        # 루트가 내부 노드인데 키가 하나도 없어지면 높이 감소
        if not self.root.is_leaf and len(self.root.keys) == 0:
            self.root = self.root.children[0]

    def _delete_recursive(self, node, parent, parent_idx, key):
        if node.is_leaf:
            i = node.find_index(key)
            if i < len(node.keys) and node.keys[i] == key:
                node.keys.pop(i)
                node.rids.pop(i)

                # 리프 노드 Underflow 처리
                if parent and len(node.keys) < self.min_keys_leaf:
                    self._handle_leaf_underflow(node, parent, parent_idx)
        else:
            i = node.find_index(key)
            self._delete_recursive(node.children[i], node, i, key)

            # 내부 노드 Underflow 처리
            if parent and len(node.keys) < self.min_keys_internal:
                self._handle_internal_underflow(node, parent, parent_idx)

    def _handle_leaf_underflow(self, leaf, parent, i):
        """리프 노드 Underflow: 형제에게서 빌리거나 병합합니다."""
        # 1. 왼쪽 형제 확인
        if i > 0 and len(parent.children[i - 1].keys) > self.min_keys_leaf:
            left_sibling = parent.children[i - 1]
            leaf.keys.insert(0, left_sibling.keys.pop())
            leaf.rids.insert(0, left_sibling.rids.pop())
            parent.keys[i - 1] = leaf.keys[0] # 라우팅 키 업데이트
            return

        # 2. 오른쪽 형제 확인
        if i < len(parent.keys) and len(parent.children[i + 1].keys) > self.min_keys_leaf:
            right_sibling = parent.children[i + 1]
            leaf.keys.append(right_sibling.keys.pop(0))
            leaf.rids.append(right_sibling.rids.pop(0))
            parent.keys[i] = right_sibling.keys[0] # 라우팅 키 업데이트
            return

        # 3. 병합 (Merge)
        if i > 0:
            # 왼쪽 형제와 병합
            left_sibling = parent.children[i - 1]
            left_sibling.keys.extend(leaf.keys)
            left_sibling.rids.extend(leaf.rids)
            left_sibling.next_leaf = leaf.next_leaf # 링크드 리스트 갱신
            parent.keys.pop(i - 1)
            parent.children.pop(i)
        else:
            # 오른쪽 형제와 병합
            right_sibling = parent.children[i + 1]
            leaf.keys.extend(right_sibling.keys)
            leaf.rids.extend(right_sibling.rids)
            leaf.next_leaf = right_sibling.next_leaf # 링크드 리스트 갱신
            parent.keys.pop(i)
            parent.children.pop(i + 1)

    def _handle_internal_underflow(self, node, parent, i):
        """내부 노드 Underflow 로직 (B-tree의 방식과 거의 동일)"""
        if i > 0 and len(parent.children[i - 1].keys) > self.min_keys_internal:
            left_sibling = parent.children[i - 1]
            node.keys.insert(0, parent.keys[i - 1])
            node.children.insert(0, left_sibling.children.pop())
            parent.keys[i - 1] = left_sibling.keys.pop()
            return

        if i < len(parent.keys) and len(parent.children[i + 1].keys) > self.min_keys_internal:
            right_sibling = parent.children[i + 1]
            node.keys.append(parent.keys[i])
            node.children.append(right_sibling.children.pop(0))
            parent.keys[i] = right_sibling.keys.pop(0)
            return

        # 병합
        if i > 0:
            left_sibling = parent.children[i - 1]
            left_sibling.keys.append(parent.keys.pop(i - 1))
            left_sibling.keys.extend(node.keys)
            left_sibling.children.extend(node.children)
            parent.children.pop(i)
        else:
            right_sibling = parent.children[i + 1]
            node.keys.append(parent.keys.pop(i))
            node.keys.extend(right_sibling.keys)
            node.children.extend(right_sibling.children)
            parent.children.pop(i + 1)
